version: 1
formatters:
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
  file:
    class: logging.FileHandler
    filename: logs/app.log
    level: DEBUG
    formatter: detailed
    mode: 'a'  # Append mode
loggers:
  graph_builder:
    level: DEBUG
    handlers: [console, file]
  moa_star:
    level: DEBUG
    handlers: [console, file]
  route_constructor:
    level: DEBUG
    handlers: [console, file]
  geocoding:
    level: DEBUG
    handlers: [console, file]
  validators:
    level: DEBUG
    handlers: [console, file]  # Corrected from 'console脏污 file'
root:
  level: INFO
  handlers: [console]